
spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.132.161.199:3306/psycholog
    username: root
    password: root

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

jpa:
    hibernate:
    ddl-auto: update
    naming:
    physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

